INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Bienes de Uso', 70, 'BIUSO', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Cargos Diferidos', 80, 'CADIF', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Caja y Bancos', 20, 'CAJA', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Cuentas por Cobrar', 40, 'CLIEN', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Deudas Fiscales', 40, 'DSFIC', '2')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Deudas Financieras', 30, 'DSFIN', '2')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Otras Deudas', 50, 'DSOTR', '2')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Deudas Sociales', 20, 'DSSOC', '2')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Intangibles', 90, 'INTAN', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Inversiones', 30, 'INVER', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Bienes de Cambio', 60, 'MERCA', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Cuentas de Orden', 20, 'ORDEN', '4')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Otras Cuentas x Cobrar', 50, 'OTCOB', '1')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Cuentas a Pagar', 10, 'PROVE', '2')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Provisiones', 60, 'PROVI', '2')
INSERT INTO conSituPatri(Descripcion, Orden, Rubro_Balance, Rubro_Id) VALUES('Según Evolución Patrimonio Neto', 10, 'SEPN', '3')
