INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('AFAM', 'ACTIVO FIJO AMORTIZACIONES')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('AFVO', 'ACTIVO FIJO VALOR ORIGEN')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('ANFCL', 'Anticipo financiero de clientes')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('ANTCL', 'Anticipos de clientes en cta. cte.')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('ANTPR', 'Anticipo a proveedores')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('BANCO', 'Bancos propios')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('CDADE', 'Cheques diferidos a debitar')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('CHEQC', 'Cheques de clientes')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('CLIEN', 'Clientes. Deudores por ventas')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('COSTO', 'Costo')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('DESCU', 'Descuentos de ventas')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('DEVO', 'Devoluciones de ventas')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('EFECT', 'Efectivo')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('FACAR', 'Facturas a recibir')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('INVEN', 'Inventarios')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('MTRAI', 'Mercadería en transito import')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('MTRAN', 'Mercadería en tránsito')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('PROME', 'Proveedores menores')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('PROVE', 'Proveedores')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('RESAC', 'RESULTADOS ACUMULADOS')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('RESUL', 'RESULTADOS DEL EJERCICIO')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('RETCL', 'Retención de clientes')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('RETPR', 'Retención a proveedores')
INSERT INTO conTipoEspeciales(TipoEspe_Id, Descripcion) VALUES('VENTA', 'Ventas')
GO

INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('AFAM', 'AMACD')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('AFAM', 'AMACU')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('AFVO', 'BIUSO')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('AFVO', 'CADIF')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('ANFCL', 'ANTCL')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('ANTCL', 'ANTCL')
--INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('ANTPR', 'ANTPR')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('ANTPR', 'OTCBC')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('ANTPR', 'OTCOB')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('ANTPR', 'PADEL')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('BANCO', 'BANCO')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('CDADE', 'CDADE')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('CHEQC', 'CHEQ')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('CLIEN', 'CLIEN')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('COSTO', 'COSTO')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('DESCU', 'DESOB')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('DESCU', 'VENTA')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('DEVO', 'VENTA')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('EFECT', 'EFEC')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('FACAR', 'FACAR')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('INVEN', 'MERCA')
--INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('MTRAI', 'INVEN')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('MTRAI', 'MERCA')
--INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('MTRAN', 'INVEN')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('MTRAN', 'MERCA')
--INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('PROME', 'DSDIV')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('PROME', 'PROFF')
--INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('PROVE', 'DSDIV')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('PROVE', 'PROVE')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('RESAC', 'REACU')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('RESAC', 'REEJE')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('RESUL', 'REEJE')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('RETCL', 'RETCL')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('RETPR', 'RETPR')
INSERT INTO conTipoEspecialesCuerpo(TipoEspe_Id, Tipo_Id) VALUES('VENTA', 'VENTA')
GO