insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1500, 'Sueldos')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1501, 'Actividades')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1502, 'Afore')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1503, 'Condicion Servicio')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1504, 'Estado Civil')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1505, 'Localidad')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1506, 'Modalidad Contratacion')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1507, 'Sinestrado')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1508, 'Situacion Revi')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1509, 'TipoContrato')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1510, 'TipoEmpleador')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1511, 'Tipo Jornada')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1512, 'Tipo Regimen')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1513, 'Tipo SDI')
insert into genEntidadesBasicas (Entidad_Id, Descripcion) values (1514, 'Codigo Natural')

insert into genVersion (Version) values(512.02)
